import * as fs from "fs";
import * as path from "path";
import type { HardhatRuntimeEnvironment } from "hardhat/types";

export const frontendAbiDir = path.resolve(__dirname, "../../../src/lib/abi");
export const deploymentsDir = path.resolve(__dirname, "../../deployments");

const EXPORTED = ["PixelMarket"] as const;

export type DeploymentRecord = {
  network: string;
  chainId: number;
  deployer: string;
  ponsFactory: string;
  forwarder: string;
  market: string;
  deployedAt: string;
  txHash: string | null;
  block: number | null;
};

/**
 * Writes each exported contract's ABI to ../src/lib/abi/<Name>.abi.json as a
 * plain JSON array, so the front end imports it through a typed wrapper
 * and viem infers argument types — and its creation bytecode to
 * <Name>.bytecode.json: the site deploys the market from a wallet through
 * the deterministic deployer, so the bytecode the site embeds is what fixes
 * the market's address.
 */
export async function exportAbis(hre: HardhatRuntimeEnvironment): Promise<void> {
  fs.mkdirSync(frontendAbiDir, { recursive: true });
  for (const name of EXPORTED) {
    const artifact = await hre.artifacts.readArtifact(name);
    fs.writeFileSync(path.join(frontendAbiDir, `${name}.abi.json`), JSON.stringify(artifact.abi, null, 2) + "\n");
    // The same ABI as a TypeScript `as const` literal, so viem infers types.
    const ident = name[0].toLowerCase() + name.slice(1) + "Abi";
    fs.writeFileSync(
      path.join(frontendAbiDir, `${ident}.ts`),
      `// Generated by contracts/scripts/lib/exportAbi.ts on every hardhat compile — do not edit.\nexport const ${ident} = ${JSON.stringify(artifact.abi, null, 2)} as const;\n`,
    );
    const build = await hre.artifacts.getBuildInfo(`${artifact.sourceName}:${name}`);
    const record = {
      contractName: name,
      sourceName: artifact.sourceName,
      solcVersion: build?.solcVersion ?? null,
      optimizer: build?.input.settings.optimizer ?? null,
      viaIR: Boolean(build?.input.settings.viaIR),
      bytecode: artifact.bytecode,
    };
    fs.writeFileSync(path.join(frontendAbiDir, `${name}.bytecode.json`), JSON.stringify(record, null, 2) + "\n");
  }
}
